config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  resources :categories do
    resources :products 
    
  end

  root to: "home#index"
  get '/users' => 'home#user'
  post '/home/change_role' => 'home#change_role'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def user
    @users = User.all.reject{|u| u.email == "admin@admin.com" }
  end
  def change_role
    User.find(params[:id]).roles.first.update_attributes(:name => params[:role])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%div#accordion
  -@categories.each do |cat|
    .panel.panel-default.m-bottom
      %h3.panel-heading.m-pointer #{cat.name}
      .panel-body
        - if cat.products.count == 0
          %h5.center No product found in this category 
        - else
          %table.table.table-hover.table-bordered.table-responsive
            %thead
              %tr
                %th Name
                %th Descrption
                - if current_user && (current_user.role? :admin)
                  %th Actions
            %tbody
              -cat.products.each do |pro|
                %tr
                  %td= pro.name
                  %td= pro.description
                  - if current_user && (current_user.role? :admin)
                    %td
                      = link_to 'Show', category_product_path(cat,pro)
                      = link_to 'Edit', edit_category_product_path(cat,pro)
                      = link_to 'Destroy', category_product_path(cat,pro), :method => :delete, :data => { :confirm => 'Are you sure?' }
              

app/views/home/user.html.haml
%h1.text-center Users
%table.table
  %thead
    %tr
      %th Email
      %th Role
  %tbody
    - @users.each do |a|
      %tr
        %td
          = a.email
        %td.change_role{:id => "#{a.id}"}
          = select("role", "val", ["admin","user"],:selected => a.roles.first.name)