config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  resources :categories do
    resources :products 
    
  end

  root to: "home#index"
  get '/users' => 'home#user'
  post '/home/change_role' => 'home#change_role'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates_presence_of :name, :description
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products
  end

  # GET /categories/new
  def new
    if current_user.role? :admin
      @category = Category.new
    else
      redirect_to root_url, :alert => "You are not authorized"
    end
  end

  # GET /categories/1/edit
  def edit
    unless current_user.role? :admin
      redirect_to root_url, :alert => "You are not authorized"
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if current_user.role? :admin
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    else
      redirect_to root_url, :alert => "You are not authorized"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .panel.panel-default
    .panel-heading
      %b Category Name:
      = f.text_field :name
    .panel-body
      %b Description:
      = f.text_field :description
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category, class: "btn btn-primary"
\|
= link_to 'Back', categories_path, class: "btn btn-primary"

app/views/categories/index.html.haml
%h1.text-center Categories

%table.table.table-striped
  - @categories.each do |cat|
    %tr
      %td
        = link_to cat.name, category_path(:id => cat.id)
      %td= link_to 'Edit', edit_category_path(cat)
      %td= link_to 'Delete', cat, :method => :delete, :data => { :confirm => 'Are you sure?' }

%div
  = link_to 'New Category', new_category_path, class: "btn btn-primary"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path, class: "btn btn-mini btn-default"

app/views/categories/show.html.haml
.panel.panel-default
  .panel-heading
    %b Category Name:
    = @category.name
  .panel-body
    %b Description:
    = @category.description

%br
%h2 Products:
%table.table.table-striped
  - if @products.empty?
    %h3 No product to Display
  -else
    -@products.each_with_index do |product,index|
      %tr
        %td
          = index+1
        %td
          = link_to product.name, category_product_path(:id => product.id, :category_id => params[:id])
        %td
          = link_to "Delete", category_product_path(:id => product.id, :category_id => params[:id]), :method => "delete"
          %br
%h3
  = link_to 'Add New Product', new_category_product_path(@category), class: "btn btn-primary"