config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  resources :categories do
    resources :products 
    
  end

  root to: "home#index"
  get '/users' => 'home#user'
  post '/home/change_role' => 'home#change_role'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
   validates_presence_of :name, :description
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @category = Category.find(params[:category_id])
    @product = @category.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to category_path(:id => params[:category_id]), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if current_user.role? :admin
      @product.destroy
      respond_to do |format|
        format.html { redirect_to category_url(:id => params[:category_id]) }
        format.json { head :no_content }
      end
     else
       redirect_to root_url, :alert => "You are not authorized"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, url: {action: "create", controller: "products"} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .panel.panel-default
    .panel-heading
      %b 
        = f.label :name
      = f.text_field :name
    .panel-body
      %b 
        = f.label :description
      = f.text_field :description
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Back', category_products_path, class: "btn btn-primary"

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.description
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path, class: "btn-primary"

app/views/products/new.html.haml
%h1 New Product

= render 'form'
= link_to 'Back', category_path(:id => params[:category_id]), class: "btn btn-default"

app/views/products/show.html.haml
%p#notice= notice

.panel.panel-default
  .panel-heading
    %b Product Name:
    = @product.name
  .panel-body
    %b Product Description:
    = @product.description

-#= link_to 'Edit', edit_product_path(@product)
= link_to 'Back', category_path(:id => params[:category_id]), class: "btn btn-default"